# Cloudflare Worker configuration - Relay Crawler
name = "relay-crawler"
main = "src/relay-crawler-worker.ts"
compatibility_date = "2023-05-18"

# Worker compatibility settings
compatibility_flags = ["nodejs_compat"]

# KV Namespace binding - shared with notification system
# For development, create namespace with: wrangler kv:namespace create "relay_crawler"
[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID" # Replace with: wrangler kv:namespace create "relay_crawler"
preview_id = "YOUR_KV_PREVIEW_ID" # Replace with: wrangler kv:namespace create "relay_crawler" --preview

# Environment variables (non-sensitive)
[vars]
RELAY_URLS = "wss://relay.primal.net,wss://relay.damus.io,wss://relay.nostr.band,wss://nos.lol,wss://relay.snort.social"

# Cron trigger - runs every minute
[triggers]
crons = ["* * * * *"] # Every minute

# Production environment
[env.production]
name = "relay-crawler-prod"
[env.production.vars]
RELAY_URLS = "wss://relay.chorus.community/,wss://relay.primal.net,wss://relay.damus.io,wss://nos.lol,wss://relay.snort.social,wss://relay.nostr.band"
[[env.production.kv_namespaces]]
binding = "KV"
id = "PRODUCTION_KV_NAMESPACE_ID" # Replace with production KV namespace ID

# Staging environment
[env.staging]
name = "relay-crawler-staging"
[env.staging.vars]
RELAY_URLS = "wss://relay.primal.net,wss://relay.damus.io"
[[env.staging.kv_namespaces]]
binding = "KV"
id = "STAGING_KV_NAMESPACE_ID" # Replace with staging KV namespace ID

# Resource limits
[limits]
cpu_ms = 50 # 50ms CPU time per request

# Secrets (set via wrangler CLI or dashboard):
# - WORKER_AUTH_TOKEN (optional, for manual trigger authentication)